ascii_letters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
widget_types = ["arc", 
                "bar", "button", "buttonmatrix", 
                "calendar", "canvas", "chart", "checkbox", 
                "dropdown", 
                "image", "imagebutton", 
                "keyboard", 
                "label", "led", "line", "list", 
                "menu", "messagebox", 
                "roller", 
                "scale", "slider", "spangroup", "spinbox", "spinner", "switch", 
                "table", "tabview", "textarea", "tileview", 
                "window"]
implemented_types = ["arc", 
                     "bar", "button", "buttonmatrix", 
                     "calendar", "checkbox", 
                     "dropdown", 
                     "label", "led", 
                     "roller", 
                     "scale", "slider", "spinbox", "switch", 
                     "table", "textarea"]